networks:
  app-tier:
    driver: bridge

services:
  node:
    build:
      context: .
      dockerfile: ./js.Dockerfile
      target: node-pg-ws
    networks:
      - app-tier
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_PASSWORD=xrpsql
      - POSTGRESQL_USERNAME=xrpsql
      - POSTGRESQL_DATABASE=xrpsql
    volumes:
      - ./postgresql:/bitnami/postgresql
    ports:
      - "5433:5432"
    networks:
      - app-tier
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-tier
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    # user:
    #   -
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks:
      - app-tier
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - 4321:5432
    environment:
      POSTGRES_USER: xrpsql
      POSTGRES_PASSWORD: xrpsql
    volumes:
      - /data/timescaledb:/var/lib/postgresql/data
    networks:
      - app-tier
# volumes:
#   grafana-data
